// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Versatus.GestaoFinanceira.Infrastructure;

#nullable disable

namespace Versatus.GestaoFinanceira.Infrastructure.Migrations
{
    [DbContext(typeof(GestaoFinanceiraDbContext))]
    partial class GestaoFinanceiraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.CaixaBanco", b =>
                {
                    b.Property<int>("IdCaixaBanco")
                        .HasColumnType("int")
                        .HasColumnName("IDFINCAIXABANCO");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOFILIAL");

                    b.Property<short>("Ativo")
                        .HasColumnType("smallint")
                        .HasColumnName("ATIVO");

                    b.Property<string>("ContaContabil")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CONTACONTABIL");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAINCLUSAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<short>("EntraFluxoCaixa")
                        .HasColumnType("smallint")
                        .HasColumnName("ENTRAFLUXOCAIXA");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAALTERACAO");

                    b.Property<DateTime?>("HoraInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAINCLUSAO");

                    b.Property<int?>("IdPlanoContabil")
                        .HasColumnType("int")
                        .HasColumnName("IDCONPLANOCONTABIL");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOALTERACAO");

                    b.Property<int?>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOINCLUSAO");

                    b.Property<decimal?>("Saldo")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("SALDO");

                    b.Property<int>("TipoConta")
                        .HasColumnType("int")
                        .HasColumnName("IDTIPOCONTA");

                    b.Property<int?>("TipoContaCaixa")
                        .HasColumnType("int")
                        .HasColumnName("IDTIPOCONTACAIXA");

                    b.Property<DateTime?>("UltimaDataConferida")
                        .HasColumnType("datetime")
                        .HasColumnName("ULTIMADATACONFERIDA");

                    b.HasKey("IdCaixaBanco", "IdFilial");

                    b.ToTable("FINCAIXABANCO", (string)null);
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.CaixaBancoUsuario", b =>
                {
                    b.Property<int>("IdCaixaBanco")
                        .HasColumnType("int")
                        .HasColumnName("IDFINCAIXABANCO");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOFILIAL");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAINCLUSAO");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAALTERACAO");

                    b.Property<DateTime?>("HoraInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAINCLUSAO");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOALTERACAO");

                    b.Property<int?>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOINCLUSAO");

                    b.HasKey("IdCaixaBanco", "IdFilial", "IdUsuario");

                    b.ToTable("FINCAIXABANCOUSUARIO", (string)null);
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.Cobrador", b =>
                {
                    b.Property<int>("IdCobrador")
                        .HasColumnType("int")
                        .HasColumnName("IDFINCOBRADOR");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOFILIAL");

                    b.Property<short>("Ativo")
                        .HasColumnType("smallint")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAINCLUSAO");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAALTERACAO");

                    b.Property<DateTime?>("HoraInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAINCLUSAO");

                    b.Property<int>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOENTIDADE");

                    b.Property<int?>("IdMeioContato")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOMEIOCONTATO");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIO");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOALTERACAO");

                    b.Property<int?>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOINCLUSAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.HasKey("IdCobrador", "IdFilial");

                    b.ToTable("FINCOBRADOR", (string)null);
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.ContaBancaria", b =>
                {
                    b.Property<int>("IdCaixaBanco")
                        .HasColumnType("int")
                        .HasColumnName("IDFINCAIXABANCO");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOFILIAL");

                    b.Property<short>("BoletoBeneficiarioDiferente")
                        .HasColumnType("smallint")
                        .HasColumnName("BOLETOBENEFICIARIODIFERENTE");

                    b.Property<short>("BoletoSacadoAvalista")
                        .HasColumnType("smallint")
                        .HasColumnName("BOLETOSACADOAVALISTA");

                    b.Property<decimal?>("ChequePendente")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("CHEQUEPENDENTE");

                    b.Property<int>("ContaBancariaTipo")
                        .HasColumnType("int")
                        .HasColumnName("IDTIPOCONTABANCARIA");

                    b.Property<short>("ContaTerceiro")
                        .HasColumnType("smallint")
                        .HasColumnName("CONTATERCEIRO");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CPFCNPJ");

                    b.Property<decimal?>("CreditoPendente")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("CREDITOPENDENTE");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAINCLUSAO");

                    b.Property<decimal?>("DebitoPendente")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("DEBITOPENDENTE");

                    b.Property<string>("DigitoConta")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("DIGITOCONTA");

                    b.Property<short>("EnviarSped")
                        .HasColumnType("smallint")
                        .HasColumnName("ENVIARSPED");

                    b.Property<short>("GeraBoleto")
                        .HasColumnType("smallint")
                        .HasColumnName("GERABOLETO");

                    b.Property<short>("GeraRemessa")
                        .HasColumnType("smallint")
                        .HasColumnName("GERAREMESSA");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAALTERACAO");

                    b.Property<DateTime?>("HoraInclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("HORAINCLUSAO");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOAGENCIA");

                    b.Property<int?>("IdContaBancariaVinculada")
                        .HasColumnType("int")
                        .HasColumnName("IDFINCONTABANCARIAVINCULADA");

                    b.Property<int?>("IdInstituicaoFinanceira")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOINSTITUICAOFINANCEIRA");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOALTERACAO");

                    b.Property<int?>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOUSUARIOINCLUSAO");

                    b.Property<decimal?>("Limite")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("LIMITE");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("NUMEROCONTA");

                    b.Property<short>("PermiteEmitirCheque")
                        .HasColumnType("smallint")
                        .HasColumnName("PERMITEEMITIRCHEQUE");

                    b.Property<short>("ProcessaRetorno")
                        .HasColumnType("smallint")
                        .HasColumnName("PROCESSARETORNO");

                    b.Property<string>("Titular")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TITULAR");

                    b.HasKey("IdCaixaBanco", "IdFilial");

                    b.ToTable("FINCONTABANCARIA", (string)null);
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.SaldoCaixaBanco", b =>
                {
                    b.Property<int>("IdCaixaBanco")
                        .HasColumnType("int")
                        .HasColumnName("IDFINCAIXABANCO");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOFILIAL");

                    b.Property<DateTime>("DataSaldo")
                        .HasColumnType("datetime")
                        .HasColumnName("DATASALDO");

                    b.Property<short>("Conferido")
                        .HasColumnType("smallint")
                        .HasColumnName("CONFERIDO");

                    b.Property<decimal?>("SaldoAnterior")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("SALDOANTERIOR");

                    b.Property<decimal?>("SaldoAnteriorConciliado")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("SALDOANTERIORCONCILIADO");

                    b.Property<decimal?>("TotalCredito")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALCREDITO");

                    b.Property<decimal?>("TotalCreditoConciliado")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALCREDITOCONCILIADO");

                    b.Property<decimal?>("TotalDebito")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALDEBITO");

                    b.Property<decimal?>("TotalDebitoConciliado")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALDEBITOCONCILIADO");

                    b.HasKey("IdCaixaBanco", "IdFilial", "DataSaldo");

                    b.ToTable("FINSALDOCAIXABANCO", (string)null);
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.SaldoRateio", b =>
                {
                    b.Property<DateTime>("DataSaldo")
                        .HasColumnType("datetime")
                        .HasColumnName("DATASALDO");

                    b.Property<int?>("IdCentroCusto")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOCENTROCUSTO");

                    b.Property<int?>("IdClasse")
                        .HasColumnType("int")
                        .HasColumnName("IDFINCLASSE");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOFILIAL");

                    b.Property<int?>("IdProjeto")
                        .HasColumnType("int")
                        .HasColumnName("IDGLOPROJETOS");

                    b.Property<decimal?>("SaldoAnteriorEconomico")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("SALDOANTERIORECONOMICO");

                    b.Property<decimal?>("SaldoAnteriorFinanceiro")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("SALDOANTERIORFINANCEIRO");

                    b.Property<decimal?>("TotalCreditoEconomico")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALCREDITOECONOMICO");

                    b.Property<decimal?>("TotalCreditoFinanceiro")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALCREDITOFINANCEIRO");

                    b.Property<decimal?>("TotalDebitoEconomico")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALDEBITOECONOMICO");

                    b.Property<decimal?>("TotalDebitoFinanceiro")
                        .HasPrecision(23, 8)
                        .HasColumnType("decimal(23,8)")
                        .HasColumnName("TOTALDEBITOFINANCEIRO");

                    b.ToTable("FINSALDORATEIO", (string)null);
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.CaixaBancoUsuario", b =>
                {
                    b.HasOne("Versatus.GestaoFinanceira.Domain.Bancos.CaixaBanco", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCaixaBanco", "IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.ContaBancaria", b =>
                {
                    b.HasOne("Versatus.GestaoFinanceira.Domain.Bancos.CaixaBanco", null)
                        .WithOne()
                        .HasForeignKey("Versatus.GestaoFinanceira.Domain.Bancos.ContaBancaria", "IdCaixaBanco", "IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.SaldoCaixaBanco", b =>
                {
                    b.HasOne("Versatus.GestaoFinanceira.Domain.Bancos.CaixaBanco", null)
                        .WithMany()
                        .HasForeignKey("IdCaixaBanco", "IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Versatus.GestaoFinanceira.Domain.Bancos.CaixaBanco", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
