// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Versatus.AcessoGlobal.Infrastructure;

#nullable disable

namespace Versatus.AcessoGlobal.Migrations
{
    [DbContext(typeof(AcessoGlobalDbContext))]
    [Migration("20260605204815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCategoria");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdCategoriaPai")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCategoriaPai");

                    b.Property<int>("IdSinteticoAnalitico")
                        .HasColumnType("int")
                        .HasColumnName("IdSinteticoAnalitico");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdCategoriaPai");

                    b.ToTable("GloCategoria", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.CentroCusto", b =>
                {
                    b.Property<int>("IdCentroCusto")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCentroCusto");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CodigoFormatado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Extenso");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdCentroCustoPai")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCentroCustoPai");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IdGloFilial");

                    b.Property<int>("IdSinteticoAnalitico")
                        .HasColumnType("int")
                        .HasColumnName("IdSinteticoAnalitico");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<int>("Nivel")
                        .HasColumnType("int")
                        .HasColumnName("Nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.HasKey("IdCentroCusto");

                    b.HasIndex("IdCentroCustoPai");

                    b.HasIndex("IdFilial");

                    b.ToTable("GloCentroCusto", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .HasColumnType("int")
                        .HasColumnName("IdFinClasse");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CodigoFormatado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Extenso");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdClassePai")
                        .HasColumnType("int")
                        .HasColumnName("IdFinClassePai");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IdGloFilial");

                    b.Property<int>("IdSinteticoAnalitico")
                        .HasColumnType("int")
                        .HasColumnName("IdSinteticoAnalitico");

                    b.Property<int>("IdTipoNatureza")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoNatureza");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<int>("Nivel")
                        .HasColumnType("int")
                        .HasColumnName("Nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdClassePai");

                    b.HasIndex("IdFilial");

                    b.ToTable("FinClasse", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Configuration.Parametro", b =>
                {
                    b.Property<int>("IdParam")
                        .HasColumnType("int")
                        .HasColumnName("IdGloParametro");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Descricao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IdTipoValor");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Objeto");

                    b.HasKey("IdParam");

                    b.ToTable("GloParametro", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Configuration.SerieDocumento", b =>
                {
                    b.Property<int>("IdSerie")
                        .HasColumnType("int")
                        .HasColumnName("IdSequencialSerieDocto");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("IdGloSerieDocumento");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ModeloFiscal");

                    b.Property<int>("ProximoNumero")
                        .HasColumnType("int")
                        .HasColumnName("ProximoNumero");

                    b.HasKey("IdSerie");

                    b.ToTable("GloSerieDocumento", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Configuration.SerieDocumentoFilial", b =>
                {
                    b.Property<int>("IdRelacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGloSerieDocumentoFilial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRelacao"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IdGloFilial");

                    b.Property<int>("IdSerie")
                        .HasColumnType("int")
                        .HasColumnName("IdSequencialSerieDocto");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<int>("ProximoNumero")
                        .HasColumnType("int")
                        .HasColumnName("ProximoNumero");

                    b.HasKey("IdRelacao");

                    b.HasIndex("IdFilial");

                    b.HasIndex("IdSerie");

                    b.ToTable("GloSerieDocumentoFilial", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCliente");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit")
                        .HasColumnName("Bloqueado");

                    b.Property<string>("CodigoAlternativo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodigoAlternativo");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAdmissao");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<bool>("EnviarCNDNFe")
                        .HasColumnType("bit")
                        .HasColumnName("EnviarCNDNFe");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime?>("HoraCobranca")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraCobranca");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCategoria");

                    b.Property<int?>("IdClienteConceito")
                        .HasColumnType("int")
                        .HasColumnName("IdGloClienteConceito");

                    b.Property<int?>("IdDiaSemanaCobranca")
                        .HasColumnType("int")
                        .HasColumnName("IdDiaSemanaCobranca");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<int>("ImovelTipo")
                        .HasColumnType("int")
                        .HasColumnName("IdImovel");

                    b.Property<string>("InscricaoProdutor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("InscricaoProdutor");

                    b.Property<bool>("ItemFinanceiroPadrao")
                        .HasColumnType("bit")
                        .HasColumnName("ItemFinanceiroPadrao");

                    b.Property<double>("LimiteCredito")
                        .HasColumnType("float")
                        .HasColumnName("LimiteCredito");

                    b.Property<string>("LocalTrabalho")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LocalTrabalho");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Profissao");

                    b.Property<double>("RendaMensal")
                        .HasColumnType("float")
                        .HasColumnName("RendaMensal");

                    b.Property<int>("SituacaoSPC")
                        .HasColumnType("int")
                        .HasColumnName("SituacaoClienteSPC");

                    b.Property<string>("TelefoneTrabalho")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TelefoneTrabalho");

                    b.Property<double>("ValorAluguel")
                        .HasColumnType("float")
                        .HasColumnName("ValorAluguel");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdCategoria");

                    b.ToTable("GloCliente", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.DadosPessoaFisica", b =>
                {
                    b.Property<int>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEntidade");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DataEmissaoRg")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataEmissaoRg");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataNascimento");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int")
                        .HasColumnName("IdEstadoCivil");

                    b.Property<bool>("FisicaTipoJuridica")
                        .HasColumnType("bit")
                        .HasColumnName("FisicaTipoJuridica");

                    b.Property<string>("OrgaoEmissorRg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("OrgaoEmissorRg");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Rg");

                    b.Property<int>("Sexo")
                        .HasColumnType("int")
                        .HasColumnName("IdSexo");

                    b.HasKey("IdEntidade");

                    b.ToTable("GloEntidadeFisica", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.Property<int>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEntidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<int>("Enquadramento")
                        .HasColumnType("int")
                        .HasColumnName("IdEnquadramento");

                    b.Property<int?>("IdCnaePrincipal")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCnaePrincipal");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RazaoSocial");

                    b.Property<int>("RegimeTributario")
                        .HasColumnType("int")
                        .HasColumnName("IdRegimeTributario");

                    b.HasKey("IdEntidade");

                    b.ToTable("GloEntidadeJuridica", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Entidade", b =>
                {
                    b.Property<int>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEntidade");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<int>("ContribuinteICMS")
                        .HasColumnType("int")
                        .HasColumnName("IDINDICADORCONTRIBUINTEICMS");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("EmailCompra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailCompra");

                    b.Property<string>("EmailFinanceiro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailFinanceiro");

                    b.Property<string>("EmailNFE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailNFE");

                    b.Property<string>("EmailVenda")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailVenda");

                    b.Property<string>("HomePage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HomePage");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int>("IdTipoPlataforma")
                        .HasColumnType("int")
                        .HasColumnName("IDTIPOPLATAFORMA");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("InscricaoEstadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("InscricaoMunicipal");

                    b.Property<string>("InscricaoSuframa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("InscricaoSuframa");

                    b.Property<bool>("IsAgenciaBancaria")
                        .HasColumnType("bit")
                        .HasColumnName("AgenciaBancaria");

                    b.Property<bool>("IsAluno")
                        .HasColumnType("bit")
                        .HasColumnName("Aluno");

                    b.Property<bool>("IsCliente")
                        .HasColumnType("bit")
                        .HasColumnName("Cliente");

                    b.Property<bool>("IsComissionado")
                        .HasColumnType("bit")
                        .HasColumnName("Comissionado");

                    b.Property<bool>("IsContador")
                        .HasColumnType("bit")
                        .HasColumnName("Contador");

                    b.Property<bool>("IsFilial")
                        .HasColumnType("bit")
                        .HasColumnName("Filial");

                    b.Property<bool>("IsFornecedor")
                        .HasColumnType("bit")
                        .HasColumnName("Fornecedor");

                    b.Property<bool>("IsFuncionario")
                        .HasColumnType("bit")
                        .HasColumnName("Funcionario");

                    b.Property<bool>("IsInstituicaoFinanceira")
                        .HasColumnType("bit")
                        .HasColumnName("InstituicaoFinanceira");

                    b.Property<bool>("IsIntermediadorComercial")
                        .HasColumnType("bit")
                        .HasColumnName("IntermediadorComercial");

                    b.Property<bool>("IsObra")
                        .HasColumnType("bit")
                        .HasColumnName("Obra");

                    b.Property<bool>("IsOutro")
                        .HasColumnType("bit")
                        .HasColumnName("Outro");

                    b.Property<bool>("IsProfessor")
                        .HasColumnType("bit")
                        .HasColumnName("Professor");

                    b.Property<bool>("IsProspecto")
                        .HasColumnType("bit")
                        .HasColumnName("Prospecto");

                    b.Property<bool>("IsRepresentante")
                        .HasColumnType("bit")
                        .HasColumnName("Representante");

                    b.Property<bool>("IsTransportadora")
                        .HasColumnType("bit")
                        .HasColumnName("Transportadora");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observacao");

                    b.Property<int>("StatusCnpjCpf")
                        .HasColumnType("int")
                        .HasColumnName("IdStatusCnpjCpf");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int")
                        .HasColumnName("IdFisicaJuridica");

                    b.HasKey("IdEntidade");

                    b.ToTable("GloEntidade", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.EntidadeEndereco", b =>
                {
                    b.Property<int>("IdEntidadeEndereco")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEntidadeEndereco");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CaixaPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CaixaPostal");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Cep");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Complemento");

                    b.Property<int?>("IdBairro")
                        .HasColumnType("int")
                        .HasColumnName("IdGloBairro");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCidade");

                    b.Property<int>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEntidade");

                    b.Property<int>("IdTipoLogradouro")
                        .HasColumnType("int")
                        .HasColumnName("IdGloTipoLogradouro");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Logradouro");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<bool>("Padrao")
                        .HasColumnType("bit")
                        .HasColumnName("Padrao");

                    b.Property<int>("TipoEndereco")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoEndereco");

                    b.HasKey("IdEntidadeEndereco");

                    b.HasIndex("IdBairro");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdEntidade");

                    b.HasIndex("IdTipoLogradouro");

                    b.ToTable("GloEntidadeEndereco", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .HasColumnType("int")
                        .HasColumnName("IdGloFornecedor");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CodigoAlternativo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodigoAlternativo");

                    b.Property<string>("ContaContabil")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ContaContabil");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCategoria");

                    b.Property<int?>("IdCondicaoPagamento")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCondicaoPagamento");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<bool>("IsFornecedorCotacao")
                        .HasColumnType("bit")
                        .HasColumnName("FornecedorCotacao");

                    b.HasKey("IdFornecedor");

                    b.HasIndex("IdCategoria");

                    b.ToTable("GloFornecedor", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("IdGloFuncionario");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CategoriaCnh")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CategoriaCnh");

                    b.Property<string>("Ctps")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ctps");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime?>("DataEmissaoCtps")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataEmissaoCtps");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("DataInscricaoPis")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInscricaoPis");

                    b.Property<DateTime?>("DataVencimentoCnh")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataVencimentoCnh");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdBancoPis")
                        .HasColumnType("int")
                        .HasColumnName("IdGloBancoPis");

                    b.Property<int?>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("IdGloPais");

                    b.Property<int?>("IdRaca")
                        .HasColumnType("int")
                        .HasColumnName("IdRhRaca");

                    b.Property<int?>("IdTipoDeficiencia")
                        .HasColumnType("int")
                        .HasColumnName("IdRhTipoDeficiencia");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("InscricaoPis")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("InscricaoPis");

                    b.Property<string>("NomeAgenciaPis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomeAgenciaPis");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomeMae");

                    b.Property<string>("NomePai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomePai");

                    b.Property<string>("NumeroAgenciaPis")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroAgenciaPis");

                    b.Property<string>("NumeroCnh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroCnh");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observacao");

                    b.Property<string>("SerieCtps")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SerieCtps");

                    b.Property<string>("UfCtps")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("UfCtps");

                    b.HasKey("IdFuncionario");

                    b.ToTable("GloFuncionario", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Transportadora", b =>
                {
                    b.Property<int>("IdTransportadora")
                        .HasColumnType("int")
                        .HasColumnName("IdGloTransportadora");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCategoria");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<int>("ProprietarioTipo")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoProprietario");

                    b.Property<string>("Rntrc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Rntrc");

                    b.Property<int>("TransportadorTipo")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTransportador");

                    b.HasKey("IdTransportadora");

                    b.HasIndex("IdCategoria");

                    b.ToTable("GloTransportadora", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Finance.Banco", b =>
                {
                    b.Property<int>("IdBanco")
                        .HasColumnType("int")
                        .HasColumnName("IdGloBanco");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("CodigoBancoCobranca");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.HasKey("IdBanco");

                    b.ToTable("GloBanco", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Finance.FormaPagamento", b =>
                {
                    b.Property<int>("IdForma")
                        .HasColumnType("int")
                        .HasColumnName("IdFormaPagamento");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SiglaForma");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoFormaPagamento");

                    b.HasKey("IdForma");

                    b.ToTable("GloFormaPagamento", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Bairro", b =>
                {
                    b.Property<int>("IdBairro")
                        .HasColumnType("int")
                        .HasColumnName("IdBairro");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int")
                        .HasColumnName("IdCidade");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.HasKey("IdBairro");

                    b.HasIndex("IdCidade");

                    b.ToTable("GloBairro", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCidade");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Cep");

                    b.Property<int>("CodigoCidade")
                        .HasColumnType("int")
                        .HasColumnName("CodigoCidade");

                    b.Property<string>("CodigoIBGE")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("CodigoIBGE");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("IdGloPais");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.Property<string>("SiglaEstado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Uf");

                    b.HasKey("IdCidade");

                    b.HasIndex("IdPais");

                    b.HasIndex("SiglaEstado");

                    b.ToTable("GloCidade", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEndereco");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Cep");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Complemento");

                    b.Property<int?>("IdBairroFinal")
                        .HasColumnType("int")
                        .HasColumnName("IdGloBairroFinal");

                    b.Property<int>("IdBairroInicial")
                        .HasColumnType("int")
                        .HasColumnName("IdGloBairroInicial");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int")
                        .HasColumnName("IdGloCidade");

                    b.Property<int>("IdTipoLogradouro")
                        .HasColumnType("int")
                        .HasColumnName("IdGloTipoLogradouro");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Logradouro");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("LONGITUDE");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdBairroFinal");

                    b.HasIndex("IdBairroInicial");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdTipoLogradouro");

                    b.ToTable("GloEndereco", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("IdSequencialEstado");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CodigoIBGE")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CodigoIBGE");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<bool>("ExigeIdentificacaoTecnico")
                        .HasColumnType("bit")
                        .HasColumnName("ExigeIdentificacaoTecnico");

                    b.Property<bool>("ExigeRegistroSistema")
                        .HasColumnType("bit")
                        .HasColumnName("ExigeRegistroSistema");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("IdGloPais");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Uf");

                    b.HasKey("IdEstado");

                    b.HasIndex("IdPais");

                    b.ToTable("GloEstado", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("IdGloPais");

                    b.Property<string>("Abreviacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Abreviacao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("CodigoBACEN")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("CodigoBACEN");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.HasKey("IdPais");

                    b.ToTable("GloPais", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.TipoLogradouro", b =>
                {
                    b.Property<int>("IdTipoLogradouro")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoLogradouro");

                    b.Property<string>("Abreviacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Abreviacao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.HasKey("IdTipoLogradouro");

                    b.ToTable("GloTipoLogradouro", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Organization.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEmpresa");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int")
                        .HasColumnName("IdGloGrupo");

                    b.Property<int>("IdTributacaoEspecial")
                        .HasColumnType("int")
                        .HasColumnName("IdTributacaoEspecial");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("MascaraCentroCusto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MascaraCentroCusto");

                    b.Property<string>("MascaraClasse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MascaraClasse");

                    b.Property<string>("MascaraPlanoContabil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MascaraPlanoContabil");

                    b.Property<string>("MascaraProjeto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MascaraProjeto");

                    b.Property<string>("MsgFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgFinal");

                    b.Property<string>("MsgInicial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgInicial");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("IdGrupo");

                    b.ToTable("GloEmpresa", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Organization.Filial", b =>
                {
                    b.Property<int>("IdFilial")
                        .HasColumnType("int")
                        .HasColumnName("IdGloFilial");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("IdGloEmpresa");

                    b.Property<byte[]>("Logomarca")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Logomarca");

                    b.Property<byte[]>("LogomarcaGrande")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("LogomarcaGrande");

                    b.Property<byte[]>("LogomarcaMedia")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("LogomarcaMedia");

                    b.HasKey("IdFilial");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("GloFilial", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Organization.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasColumnType("int")
                        .HasColumnName("IdGloGrupo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("IdGrupo");

                    b.ToTable("GloGrupo", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Security.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("IdGloPerfil");

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit")
                        .HasColumnName("Administrador");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descricao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<bool>("UsaDominioFinanceiro")
                        .HasColumnType("bit")
                        .HasColumnName("UsaDominioFinanceiro");

                    b.HasKey("IdPerfil");

                    b.ToTable("GloPerfil", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Security.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuario");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime?>("HoraAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraAlteracao");

                    b.Property<DateTime>("HoraInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HoraInclusao");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("IdGloFuncionario");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("IdGloPerfil");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioAlteracao");

                    b.Property<int>("IdUsuarioInclusao")
                        .HasColumnType("int")
                        .HasColumnName("IdGloUsuarioInclusao");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NomeAcesso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Senha");

                    b.Property<DateTime?>("UltimoLogon")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataUltimoLogon");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPerfil");

                    b.ToTable("GloUsuario", (string)null);
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.Categoria", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Classification.Categoria", "CategoriaPai")
                        .WithMany("SubCategorias")
                        .HasForeignKey("IdCategoriaPai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.CentroCusto", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Classification.CentroCusto", "CentroCustoPai")
                        .WithMany("SubCentros")
                        .HasForeignKey("IdCentroCustoPai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Versatus.AcessoGlobal.Domain.Organization.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCustoPai");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.Classe", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Classification.Classe", "ClassePai")
                        .WithMany("SubClasses")
                        .HasForeignKey("IdClassePai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Versatus.AcessoGlobal.Domain.Organization.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassePai");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Configuration.SerieDocumentoFilial", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Organization.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Versatus.AcessoGlobal.Domain.Configuration.SerieDocumento", "SerieDocumento")
                        .WithMany()
                        .HasForeignKey("IdSerie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filial");

                    b.Navigation("SerieDocumento");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Classification.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria");

                    b.HasOne("Versatus.AcessoGlobal.Domain.Entities.Entidade", "Entidade")
                        .WithOne()
                        .HasForeignKey("Versatus.AcessoGlobal.Domain.Entities.Cliente", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.DadosPessoaFisica", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Entities.Entidade", "Entidade")
                        .WithOne("PessoaFisica")
                        .HasForeignKey("Versatus.AcessoGlobal.Domain.Entities.DadosPessoaFisica", "IdEntidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Entities.Entidade", "Entidade")
                        .WithOne("PessoaJuridica")
                        .HasForeignKey("Versatus.AcessoGlobal.Domain.Entities.DadosPessoaJuridica", "IdEntidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.EntidadeEndereco", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("IdBairro")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Versatus.AcessoGlobal.Domain.Entities.Entidade", "Entidade")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdEntidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.TipoLogradouro", "TipoLogradouro")
                        .WithMany()
                        .HasForeignKey("IdTipoLogradouro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");

                    b.Navigation("Cidade");

                    b.Navigation("Entidade");

                    b.Navigation("TipoLogradouro");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Classification.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria");

                    b.HasOne("Versatus.AcessoGlobal.Domain.Entities.Entidade", "Entidade")
                        .WithOne()
                        .HasForeignKey("Versatus.AcessoGlobal.Domain.Entities.Fornecedor", "IdFornecedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Entities.Entidade", "Entidade")
                        .WithOne()
                        .HasForeignKey("Versatus.AcessoGlobal.Domain.Entities.Funcionario", "IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Transportadora", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Classification.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria");

                    b.HasOne("Versatus.AcessoGlobal.Domain.Entities.Entidade", "Entidade")
                        .WithOne()
                        .HasForeignKey("Versatus.AcessoGlobal.Domain.Entities.Transportadora", "IdTransportadora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Bairro", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Cidade", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("SiglaEstado")
                        .HasPrincipalKey("Sigla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Endereco", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Bairro", "BairroFinal")
                        .WithMany()
                        .HasForeignKey("IdBairroFinal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Bairro", "BairroInicial")
                        .WithMany()
                        .HasForeignKey("IdBairroInicial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.TipoLogradouro", "TipoLogradouro")
                        .WithMany()
                        .HasForeignKey("IdTipoLogradouro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BairroFinal");

                    b.Navigation("BairroInicial");

                    b.Navigation("Cidade");

                    b.Navigation("TipoLogradouro");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Location.Estado", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Location.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Organization.Empresa", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Organization.Grupo", "Grupo")
                        .WithMany("Empresas")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Organization.Filial", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Organization.Empresa", "Empresa")
                        .WithMany("Filiais")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Security.Usuario", b =>
                {
                    b.HasOne("Versatus.AcessoGlobal.Domain.Security.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.Categoria", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.CentroCusto", b =>
                {
                    b.Navigation("SubCentros");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Classification.Classe", b =>
                {
                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Entities.Entidade", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Organization.Empresa", b =>
                {
                    b.Navigation("Filiais");
                });

            modelBuilder.Entity("Versatus.AcessoGlobal.Domain.Organization.Grupo", b =>
                {
                    b.Navigation("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
